In [18]:
import numpy as np #import numpy
print("Numpy Version ", np.__version__)
arr = np.array([8, 4, 6, 8, 2]) #numpy array creation
print(arr) #printing numpy array

print("Type of array", type (arr)) #type check through type method
print("Dimension of array arr is", arr.ndim) #diamensions through ndim
d0= np.array(23) #numpy 0-D array creation
print("Dimension of array de is", d0.ndim)
fruit_list = ["Apple", "Mango", "Banana"]
print(fruit_list)
print("Type of fruit list is ", type (fruit_list))
fruit_list = np.array (fruit_list)
print("Type of fruit list is ", type (fruit_list))

Numpy Version  2.0.2
[8 4 6 8 2]
Type of array <class 'numpy.ndarray'>
Dimension of array arr is 1
Dimension of array de is 0
['Apple', 'Mango', 'Banana']
Type of fruit list is  <class 'list'>
Type of fruit list is  <class 'numpy.ndarray'>


In [19]:

import numpy as np
# Create a 1-D array by passing a list into NumPy's array() function.
A = np.array([8, 4, 6, 8, 2])
print(A)
# Create a 2-D array by passing a list of lists into array().
B = np.array([[1, 2, 3],[4, 5, 6] ] )
print(B)
# Create a 3-D array by passing a list of lists into array().
C = np.array([[[1, 2, 3],[4, 5, 6], [14, 15, 16] ]] )
print(C)
C_dimensions = C.ndim
print (C_dimensions)

[8 4 6 8 2]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]
  [14 15 16]]]
3


In [20]:
import numpy as np

# Create a 3x3 matrix with values ranging from 2 to 10
matrix = np.arange(2, 11).reshape(3, 3)

# Convert array to float type
matrix = matrix.astype(float)

# Flatten the array
flattened = matrix.flatten()

# Find maximum and minimum values
max_value = np.max(flattened)
min_value = np.min(flattened)

print("Matrix:\n", matrix)
print("Flattened array:", flattened)
print("Maximum value:", max_value)
print("Minimum value:", min_value)


Matrix:
 [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
Flattened array: [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
Maximum value: 10.0
Minimum value: 2.0
